default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: cart_sync_development

test:
  <<: *default
  database: cart_sync_test

production:
  <<: *default
  database: cart_sync_production
  username: cart_sync
  password: <%= ENV['CART_SYNC_DATABASE_PASSWORD'] %>
