source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.0"

# Core Rails gems
gem "rails", "~> 7.0.0"
gem "pg", "~> 1.1"
gem "puma", "~> 5.0"
gem "bootsnap", ">= 1.4.4", require: false
gem "rack-cors"

# GraphQL
gem "graphql", "~> 2.0"
gem "graphql-subscriptions", "~> 1.0"

# Redis and ActionCable
gem "redis", "~> 4.0"
gem "actioncable"

# Authentication
gem "devise"
gem "devise-jwt"

# Background jobs
gem "sidekiq"

# Testing
gem "rspec-rails"
gem "factory_bot_rails"
gem "faker"

# Development
gem "listen", "~> 3.3"
gem "spring"

group :development, :test do
  gem "byebug", platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem "rubocop", require: false
end
